language: node_js
node_js:
  - 16.15.0
cache:
directories:
  - node_modules
services:
  - mongodb
  - docker
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
install:
  - npm install
deploy:
# Production Deploy if pushing to master
- provider: script
  script: ./bin/deploy_production.sh
  on:
     branch: master